name: 'Setup'
description: 'Setup Node.js, install dependencies, and create .env file'

inputs:
  create-env:
    description: 'Whether to create .env file from environment variables'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: 🔧 Setup Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Create .env file
      if: inputs.create-env == 'true' && env.DB_PORT != '' && env.DB_USER != '' && steps.cache-env.outputs.cache-hit != 'true'
      run: |
        cat > .env << EOF
        # Database Configuration
        DB_HOST=${DB_HOST}
        DB_PORT=${DB_PORT}
        DB_USER=${DB_USER}
        DB_PASSWORD=${DB_PASSWORD}
        DB_NAME=${DB_NAME}
        # Application Configuration
        PORT=${APP_PORT}
        NODE_ENV=${NODE_ENV}
        EOF
        echo "Created .env file with configuration"
        echo "• NODE_ENV: ${NODE_ENV}"
        echo "• Configuration loaded securely"
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Setup complete
      run: |
        echo "Setup Summary:"
        echo ""
        echo "Dependencies: Freshly installed"
        # Environment file status
        if [[ "${{ inputs.create-env }}" == "true" ]]; then
          if [[ "${{ env.DB_PORT }}" != "" && "${{ env.DB_USER }}" != "" ]]; then
            if [[ "${{ steps.cache-env.outputs.cache-hit }}" == "true" ]]; then
              echo ".env file: Restored from cache"
            else
              echo ".env file: Created and cached"
            fi
          else
            echo ".env file: Skipped (missing environment variables)"
          fi
        else
          echo ".env file: Skipped (create-env=false)"
        fi
        echo ""
        echo "Node.js version: $(node --version)"
        echo "npm version: $(npm --version)"
      shell: bash
