name: CI Pipeline

permissions:
  contents: read

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
  push:
    branches: [main, develop]

# Define once, use selectively
env:
  # Database Configuration
  DB_HOST: postgres
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_NAME: ${{ secrets.DB_NAME }}
  # Application Configuration
  APP_PORT: ${{ secrets.PORT }}
  NODE_ENV: production

jobs:
  # Stage 1: Install Dependencies (and populate cache)
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup and Install Dependencies
        uses: ./.github/actions/setup-node-dependencies
        with:
          create-env: 'false'

  # Stage 2: Linting
  linting:
    name: Linting
    runs-on: ubuntu-latest
    needs: install-dependencies
    permissions:
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug - Before install
        run: |
          echo "=== Before npm ci ==="
          node --version
          npm --version
          echo "ESLint in package.json:"
          grep -i eslint package.json

      - name: Clean install with fresh package-lock
        run: |
          rm -f package-lock.json
          npm install

      - name: Verify ESLint installation
        run: |
          npm list eslint || echo "ESLint not found, installing..."
          if ! npm list eslint > /dev/null 2>&1; then
            npm install eslint @typescript-eslint/eslint-plugin @typescript-eslint/parser --save-dev
          fi
          npx eslint --version

      - name: Debug - After install
        run: |
          echo "=== After npm ci ==="
          echo "node_modules/.bin contents:"
          ls -la node_modules/.bin/ | head -20
          echo "Search for eslint:"
          find node_modules -name "*eslint*" -type f | head -10
          echo "npm list eslint:"
          npm list eslint || echo "ESLint not in npm list"
          echo "Try npx eslint --version:"
          npx eslint --version || echo "npx eslint failed"
      - name: Run ESLint
        run: npm run lint

  # Stage 3: Testing
  test:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      checks: write
    needs: install-dependencies

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup and Restore Dependencies from Cache
        uses: ./.github/actions/setup-node-dependencies
        with:
          create-env: 'false'

      - name: Run tests
        run: npm run test:cov

  # Stage 4: Security
  security:
    name: Security
    runs-on: ubuntu-latest
    needs: [linting, test]
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup and Restore Dependencies from Cache
        uses: ./.github/actions/setup-node-dependencies
        with:
          create-env: 'false'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript-typescript
          queries: security-extended,security-and-quality

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: '/language:javascript-typescript'
          upload: true

      - name: Check Dependencies Security
        run: |
          echo "Checking dependencies for security vulnerabilities..."
          if npm audit --audit-level=moderate; then
            echo "✅ No dependency vulnerabilities found"
          else
            echo "❌ Dependency vulnerabilities detected!"
            npm audit --audit-level=moderate
            exit 1
          fi

  # Stage 5: Docker Build
  docker-build:
    name: Build
    runs-on: ubuntu-latest
    needs: [linting, test, security]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-node-dependencies

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            # PR numbers
            type=ref,event=pr,prefix=pr-
            # Git commit SHA with branch prefix (only for branches)
            type=sha,prefix=main-,enable=${{ github.ref == 'refs/heads/main' }}
            type=sha,prefix=develop-,enable=${{ github.ref == 'refs/heads/develop' }}
            # Named tags for specific branches
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/develop' }}
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # Latest tag for main branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/f1-api-image.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image-${{github.sha}}
          path: /tmp/f1-api-image.tar
          retention-days: 1

  # Stage 6: Docker Publish
  docker-publish:
    name: Docker Publish
    runs-on: ubuntu-latest
    needs: [docker-build]
    # Only run when PR is successfully merged into main/develop or on version tags
    if: success() && github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v'))

    steps:
      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v3

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image-${{github.sha}}
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/f1-api-image.tar
          docker image ls -a

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}
          tags: |
            # Semantic versioning tags
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            # Named tags for specific branches
            type=raw,value=dev,enable=${{ github.ref == 'refs/heads/develop' }}
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # Latest tag for main branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Push Docker image
        run: |
          # Get the image ID from the loaded image
          IMAGE_ID=$(docker images --format "table {{.Repository}}:{{.Tag}}\t{{.ID}}" | grep "${{ github.event.repository.name }}" | head -1 | awk '{print $2}')

          # Tag and push each tag from metadata
          echo '${{ steps.meta.outputs.tags }}' | tr ',' '\n' | while read -r tag; do
            if [ ! -z "$tag" ]; then
              echo "Tagging and pushing: $tag"
              docker tag $IMAGE_ID $tag
              docker push $tag
            fi
          done

  # Stage 7: Summary
  pipeline-summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [linting, test, security, docker-build, docker-publish]
    if: always()

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run pipeline summary
        uses: ./.github/actions/pipeline-summary
        with:
          linting-result: ${{ needs.linting.result }}
          test-result: ${{ needs.test.result }}
          security-result: ${{ needs.security.result }}
          docker-build-result: ${{ needs.docker-build.result }}
          docker-publish-result: ${{ needs.docker-publish.result }}
